name = ec_transmutation
title = ExchangeClone Transmutation
description = Adds transmutation table(t)s and Tomes of Knowledge
depends = ec_core, ec_phil
optional_depends = mcl_formspec
author = ThePython10110