name = ec_armor
title = ExchangeClone Armor
description = Dark Matter and Red Matter armor
depends = ec_core, ec_matter
optional_depends = mcl_armor, 3d_armor, damage, mcl_util
author = ThePython10110