name = zzzz_exchangeclone_init
title = ExchangeClone Initialization
description = MUST be loaded before any items are registered. The "zzzz" is to (hopefully) ensure that it's the first mod to load.
author = ThePython10110