name = ec_core
title = ExchangeClone Core
description = A few necessary things, like EMC registration
depends = zzzz_exchangeclone_init, ec_lib
optional_depends = mcl_core, default, awards
author = ThePython10110