name = ec_phil
title = ExchangeClone Philosopher's Stone
description = Adds the Philosopher's Stone, used to transmute various items.
depends = ec_core
optional_depends = mcl_enchanting, mcl_crafting_table, mcl_formspec
author = ThePython10110