name = ec_upgrades
title = ExchangeClone Upgrades
description = Adds enchantments to ExchangeClone tools in MCLA/VL. Does nothing in other games.
depends = ec_core, ec_tools, ec_matter
optional_depends = mcl_enchanting, pipeworks, mcl_formspec
author = ThePython10110